### ISSUE TITLE
Criar protótipo de média/baixa fidelidade da tela de cadastro

### ISSUE THREAD

**Issue by Fealps** [fga-eps-mds/2023-1-Dnit-DOC#2]
## Descrição

Criar o protótipo de baixa fidelidade referente a US01

solves #1

**Comment by ArturRSA19** [comment]
Feito por @ArturRSA19, @avmricardo, @migueldefrias, @GuilhermeSoaress e @LeticiaResende23.


![Image](https://github.com/fga-eps-mds/2023.1-Dnit-DOC/assets/91507861/eb05070d-6f24-424e-b777-75d2f0697b35)

**Comment by JuliaSSouza** [comment]
Feito por @JuliaSSouza @CarolinaBarb @lhuck4z @Stain19 @MateusPy 

![Image](https://github.com/fga-eps-mds/2023.1-Dnit-DOC/assets/88839152/1dde8430-a5b3-4791-90a5-0ee6d3b7c161)

**Comment by Fealps** [comment]
@fga-eps-mds/2023-1-dnit-mds Muito bom, estamos aguardando a revisão por parte dos POs mas pode adicionar ambos os protótipos na documentação. Qualquer duvida podem entrar em contato 👍
