### ISSUE TITLE
Adaptação do protótipo de alta fidelidade

### ISSUE THREAD

**Issue by DenysRogeres** [fga-eps-mds/2023-1-Dnit-DOC#24]
## Design

Alterar protótipo de alta fidelidade com as seguintes adaptações pós validação:
- Remover campo MATRICULA como um dos inputs para fazer registro
- Alterar botão "Entrar" que esta na lateral do lado esquerdo e seguir padrão do portal https://servicos.dnit.gov.br/multas
- Alterar tela de login removendo o botão "cadastro" e seguir padrão do portal https://servicos.dnit.gov.br/multas

![Image](https://user-images.githubusercontent.com/54676096/238524324-1c508765-9a15-4740-bf90-c4cd16e9e835.png)

![Image](https://user-images.githubusercontent.com/54676096/238524516-0522f07a-de48-40eb-b59e-1bd56ae0e037.png) 

## D.O.D
- [x] Link do protótipo no figma
- [x] Adicionar protótipo da documentação no github pages inserindo o wireframe
- [x] Link do github pages com prototipo anexado

**Comment by ArturRSA19** [comment]
Tela de Login alterada:
<img width="718" alt="Captura de Tela 2023-05-16 às 11 15 09" src="https://github.com/fga-eps-mds/2023.1-Dnit-DOC/assets/91507861/73f92ad6-83bf-494d-81c8-876ece0d08b2">

Tela de Cadastro alterada:
<img width="714" alt="Captura de Tela 2023-05-16 às 11 15 41" src="https://github.com/fga-eps-mds/2023.1-Dnit-DOC/assets/91507861/56ac1f50-7f3c-4b4b-8e04-c5631b9ad1ae">

**Comment by DenysRogeres** [comment]
Fala Arthur! Ficou ótimo os protótipos, aqui vão alguns feedbacks para que você possa realizar a atualização:

Em relação ao à tela de Login, acho que seria melhor a gente inserir a parte de "Esqueceu senha" para de baixo do campo de senha, embora o site do DNIT utilize dessa forma, verifiquei em vários sites ligados ao governo e eles sempre adicionam essa parte abaixo do campo, então acredito que podemos lidar como um erro de desing/usabilidade no site do DNIT.

Exemplo do site do próprio acesso gov.br
![image](https://github.com/fga-eps-mds/2023.1-Dnit-DOC/assets/54676096/2eefe5bd-2bdf-4c3f-a9fc-e6f2da662404)



Em relação à tela de cadastro, acho que você poderia manter a seguinte ordem de campos para melhorar a usabilidade:

1. Nome completo
2. Email
3. Senha
4. Confirmação de senha
5. UF de lotação

Outro item é que poderíamos colocar a parte de "entrar" abaixo do botão de cadastra-se assim como está na dela do DNIT com a seguinte mensagem "Já tem cadastro? Faça o login". Daí você poderia subir a logo do DNIT para ocupar toda o central da tela

**Comment by ArturRSA19** [comment]
Tela de Login atualizada:

<img width="864" alt="Captura de Tela 2023-05-16 às 11 41 49" src="https://github.com/fga-eps-mds/2023.1-Dnit-DOC/assets/91507861/d77333bf-d18b-46d4-b4d8-7cb097a64a9d">

Tela de Cadastro atualizada:

<img width="865" alt="Captura de Tela 2023-05-16 às 11 41 21" src="https://github.com/fga-eps-mds/2023.1-Dnit-DOC/assets/91507861/5e32ef99-ccd7-4f88-a1e5-9565df36a20e">

Segue o link do FIGMA: https://www.figma.com/file/zyNXXEdSgbYnXQorSQPRgA/Protótipos-de-Alta-Fidelidade---DNIT?type=design&node-id=0-1&t=daJ4rAnQhQU3aqFi-0

**Comment by DenysRogeres** [comment]
Maravilha! Agora ficou perfeitooooooo
@LeticiaResende23 Consegue subir no github pages e mandar o link, pf?
Obs: Não esquece de alterar no histórico de edições
