### ISSUE TITLE
Criar protótipo de Média/baixa fidelidade da tela de login

### ISSUE THREAD

**Issue by Fealps** [fga-eps-mds/2023-1-Dnit-DOC#3]
## Descrição 

Criar o protótipo de baixa fidelidade referente a US03

solves #1

**Comment by ArturRSA19** [comment]
Feito por @ArturRSA19, @avmricardo, @GuilhermeSoaress. @migueldefrias e @LeticiaResende23.


![Image](https://github.com/fga-eps-mds/2023.1-Dnit-DOC/assets/91507861/90cab4af-132e-4507-93ce-0d9e1896018d)

**Comment by JuliaSSouza** [comment]
Feito por @JuliaSSouza @CarolinaBarb @lhuck4z @Stain19 @MateusPy 

![Image](https://github.com/fga-eps-mds/2023.1-Dnit-DOC/assets/88839152/2effa034-aab6-4d2c-b78e-92ee355a37e2)

**Comment by Fealps** [comment]
@fga-eps-mds/2023-1-dnit-mds Muito bom, estamos aguardando a revisão por parte dos POs mas pode adicionar ambos os protótipos na documentação. Qualquer duvida pode entrar em contato 👍
