### ISSUE TITLE
[Back] Implementação do cadastro de usuário

### ISSUE THREAD

**Issue by DenysRogeres** [fga-eps-mds/2023-1-Dnit-DOC#30]
## Implementação
Deve-se realizar a implementação do cadastro de usuário, realizando a encriptografia da senha e comunicação com banco de dado de dev

## D.O.D
- Print do swagger com endpoint
- Print do banco de dados com um usuário cadastrado

**Comment by DenysRogeres** [comment]
@avmricardo @CarolinaBarb  Fiz o merge do PR, não esqueçam de adicionar aqui o print do swagger e print do back com um cadastro realizado

**Comment by CarolinaBarb** [comment]
### Segue abaixo o print do swagger e o print do back com o cadastro realizado
![image](https://github.com/fga-eps-mds/2023.1-Dnit-DOC/assets/98655636/875a36e6-a68f-4f20-bf56-910e7bc332e0)
![image](https://github.com/fga-eps-mds/2023.1-Dnit-DOC/assets/98655636/eaee2caa-2f96-4a24-82c9-0a825f792ea3)
