### ISSUE TITLE
[Back] Implementação do login

### ISSUE THREAD

**Issue by DenysRogeres** [fga-eps-mds/2023-1-Dnit-DOC#36]
## Implementação
Deve-se realizar a implementação do loin de usuário, realizando a comunicação com banco de dado de dev

## D.O.D
- Print do swagger com endpoint
- Print do banco de dados com um usuário cadastrado

**Comment by GuilhermeSoaress** [comment]
![image](https://github.com/fga-eps-mds/2023.1-Dnit-DOC/assets/88786065/09046f46-41e3-46f1-b2c6-85fc743df374)
