### ISSUE TITLE
[Documentos] Protótipo US25

### ISSUE THREAD

**Issue by LeticiaResende23** [fga-eps-mds/2023-1-Dnit-DOC#67]
**Descrição**
Criar protótipo de alta fidelidade para US25

***Definition of Done***
- [x] Os protótipos devem ser feito no figma; 
- [x] As telas devem estar disponíveis na documentação; 
- [x] Um print das telas prototipadas devem ser comentadas nesta issue;

**Comment by LeticiaResende23** [comment]
![Image](https://github.com/fga-eps-mds/2023.1-Dnit-DOC/assets/89492943/ff297d03-f00d-4fe2-aefb-e587607b8d97)


![Image](https://github.com/fga-eps-mds/2023.1-Dnit-DOC/assets/89492943/40983f01-b540-4996-9e77-dcfd3a40c95f)

**Comment by JongaMatos** [comment]
![Tela - Solicitar ação ao DNIT](https://github.com/fga-eps-mds/2023.1-Dnit-DOC/assets/54087048/cf6e44d5-6637-49d7-a834-1b508aba8b3f)

Modificação do protótipo, validada pela Nayara, na reunião de 03/07/2023.
(Foram adicionados os campos UF e Município, para aumentar a eficiência da filtragem.
