### ISSUE TITLE
[Documentação] Sprint Planning

### ISSUE THREAD

**Issue by Fealps** [fga-eps-mds/2023-1-Dnit-DOC#7]
## Descrição

- [x] Documentar o planejamento da sprint na wiki
- [x] #8 
- [x] Sprint 1
- [x] Sprint 2
- [x] Sprint 3
- [x] Sprint 4
- [x] Sprint 5
- [x] Sprint 6
- [x] Sprint 7
- [x] Sprint 8

**Comment by antoniotoineto** [comment]
Fiz a documentação da Sprint 1 e 2, se encontra na branch 7-DocsPlanning

**Comment by antoniotoineto** [comment]
Sprints da R1 documentadas ✔️

**Comment by antoniotoineto** [comment]
Objetivos:
## US13
- Protótipos validados
- Front entregue 
- Começar Back


## US14
- Protótipos validados
- Front entregue
- Começar Back

## US06 HOTFIX
- Hotfixes do Select
- Talvez Hotfixes do Cadastro

## US07 HOTFIX
- Tudo

## US08 HOTFIX
- Tudo
