### ISSUE TITLE
[Documentação] Protótipo US13

### ISSUE THREAD

**Issue by antoniotoineto** [fga-eps-mds/2023-1-Dnit-DOC#75]
## D.O.D

- [x] Print ou link dos protótipos
- [x] Validação com Nayara

**Comment by migueldefrias** [comment]
Protótipos US13



![Image](https://github.com/fga-eps-mds/2023.1-Dnit-DOC/assets/54555684/81ab9b97-4638-4fbf-bced-48868fe55f93)







![Image](https://github.com/fga-eps-mds/2023.1-Dnit-DOC/assets/54555684/e0973c5d-9a77-4bd7-822d-92ade21db0ec)





![Image](https://github.com/fga-eps-mds/2023.1-Dnit-DOC/assets/54555684/63da5711-e9cd-4bcf-b6aa-54c8bd1c11b4)

**Comment by antoniotoineto** [comment]
Protótipo feito e validado ✅ 

![image](https://github.com/fga-eps-mds/2023-1-Dnit-DOC/assets/54555684/d8efee47-026e-419e-8264-b5ea7ae17eb7)
